# example make file
all : clean
# all : build run clean

complex :
	g++ complex.cpp -o main

selection_sort:
	g++ selection_sort.cpp -o main

insert_sort : 
	g++ insert_sort.cpp -o main

run :
	./main

clean :
	rm main